### ISSUE TITLE
Uncaught TypeError: atom.workspace.destroyActivePaneItemOrEmptyPane is not a function

### ISSUE THREAD

**Issue by abalakersky** [takkjoga/atom-vim-colon-command-on-command-pallete#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Linux Mint
**Thrown From**: [atom-vim-colon-command-on-command-pallete](https://github.com/takkjoga/atom-vim-colon-command-on-command-pallete) package, v0.2.0
### Stack Trace

Uncaught TypeError: atom.workspace.destroyActivePaneItemOrEmptyPane is not a function

```
At /home/abalakersky/.atom/packages/atom-vim-colon-command-on-command-pallete/lib/atom-vim-colon-command-on-command-pallete.coffee:37

TypeError: atom.workspace.destroyActivePaneItemOrEmptyPane is not a function
    at Object.module.exports.quit (/home/abalakersky/.atom/packages/atom-vim-colon-command-on-command-pallete/lib/atom-vim-colon-command-on-command-pallete.coffee:37:20)
    at atom-text-editor.commands.quit (/home/abalakersky/.atom/packages/atom-vim-colon-command-on-command-pallete/lib/atom-vim-colon-command-on-command-pallete.coffee:21:65)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/opt/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/opt/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/opt/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:544:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:363:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  2x -0:15.6.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.is-focused.vim-mode-plus.normal-mode)
     -0:10.4.0 vim-mode-plus:repeat-find (atom-text-editor.editor.is-focused.vim-mode-plus.normal-mode)
     -0:08.2.0 command-palette:toggle (atom-text-editor.editor.is-focused.vim-mode-plus.normal-mode)
     -0:08.0 blur (atom-text-editor.editor.is-focused.vim-mode-plus.normal-mode)
     -0:00.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:00.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.5.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:00.5.0 quit (atom-text-editor.editor.vim-mode-plus.normal-mode)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-gfm"
    ],
    "projectHome": "/home/abalakersky/Development",
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-json-editor, v0.4.1
atom-vim-colon-command-on-command-pallete, v0.2.0
atom-yamljson, v0.2.3
autocomplete-python, v1.6.1
autocomplete-ruby, v0.1.0
clipboard-plus, v0.5.1
colorful-json, v1.0.0
go-plus, v3.5.3
language-markdown, v0.11.0
linter, v1.11.3
linter-ruby, v1.2.1
markdown-themeable-pdf, v0.10.2
pretty-json, v0.4.1
python-tools, v0.6.7
ruby-block, v0.3.5
ruby-block-converter, v3.5.0
ruby-define-method, v0.2.2
vim-mode-clipboard-plus, v0.2.0
vim-mode-plus, v0.20.0

# Dev
No dev packages
```

**Comment by mattpetrie** [comment]
Looks like `atom.workspace.destroyActivePaneItemOrEmptyPane()` has been removed from Atom and replaced with `atom.workspace.destroyActivePaneItem()`. I've submitted a PR with a fix: https://github.com/takkjoga/atom-vim-colon-command-on-command-pallete/pull/3
